feat: birthday events
N3aar/Eery-Project pull request #25
Opened 2024-06-10 05:16 UTC by N3aar

2024-06-11 22:58 UTC, Psykka requested changes

2024-06-11 22:58 UTC, Psykka commented on src/commands/user/birthday.ts
O ideia nesse caso seria usar uma transaction do prisma
https://www.prisma.io/docs/orm/prisma-client/queries/transactions#interactive-transactions-1

2024-06-11 22:58 UTC, Psykka commented on src/listeners/ready.ts
> +		ensureGuilds(Array.from(client.guilds.cache.values()));
Isso vai continuar aqui mesmo em prod?

2024-06-12 00:36 UTC, N3aar commented on src/listeners/ready.ts
> +		ensureGuilds(Array.from(client.guilds.cache.values()));
sim, mas a operação foi passada para uma transaction.

2024-06-12 01:37 UTC, Psykka commented on src/commands/user/birthday.ts
> +		const birthdayDate = new Date(new Date().getFullYear(), month, day);
meses em js tem que remover -1 da index

2024-06-12 01:38 UTC, Psykka requested changes

2024-06-12 01:38 UTC, Psykka commented on src/commands/user/birthday.ts
> +		const birthdayDate = new Date(new Date().getFullYear(), month, day);
meses em js tem que remover -1 da index

2024-06-12 01:42 UTC, N3aar commented on src/commands/user/birthday.ts
> +		const birthdayDate = new Date(new Date().getFullYear(), month, day);
resolvido!

2024-06-12 01:43 UTC, Psykka approved these changes
LGTM

2024-06-12 01:43 UTC, merged